language: python
python:
  - 3.6
  - 3.7
  - 3.8-dev
install:
  - pip install -r requirements-test.txt
  - pip install -r requirements.txt
before_script:
  - mkdir -p tests/_coverage
script:
  - py.test tests/ --cov watson --cov-report term-missing
after_success:
  - coveralls --verbose
notifications:
  slack:
    secure: YZnheuWvvRWcVV9V08+k7KANIZo6+4Vk5u/rVd3tZaDlBfHOqhZcipskk/XpZQicJboDDi1x/ssuWIG3Wo9EoY1/RHUIIrBLgnIycWqHzLU8zzCO4Bb0NfwF+8B2L4GOm2qRW94l+2TDVke7719HJOo52eJ3lj7Bo8x59xVFbKw=
